#!/bin/bash

if [ ! -d ./bin ];then
mkdir ./bin;
fi

if [ ! -d ./bin/machine.list ];then
touch ./bin/machine.list
fi

#create the id_rsa.pub if it does not exist.

if [ ! -f ${HOME}/.ssh/id_rsa.pub ];then
ssh-keygen -t rsa
else
echo "id_rsa.pub already exist, just do next step to add the authoirized_keys to these ips from machine.list"
fi

AUTHORIZED_KEYS=`cat ${HOME}/.ssh/id_rsa.pub`

for i in $(cat ./bin/machine.list);do
ssh $i "cd ${HOME} && test -d .ssh || mkdir .ssh && cd .ssh && echo ${AUTHORIZED_KEYS} >> authorized_keys && chmod 600 authorized_keys "
done
